### PR TITLE
Bump elle-cli version

### PR DESCRIPTION
**Pull request by tezc**
A new version is released and causing a test failure:
https://github.com/RedisLabs/redisraft/actions/runs/3634573321/jobs/6132789114

### CODE REVIEW

**Comment by tezc** [comment]
After fix: https://github.com/tezc/redisraft/actions/runs/3637751900/jobs/6139122080

**Comment by fadidahanna** [comment]
Suggest changing `Checkout elle-cli` step to take a specific fixed version.

**Comment by tezc** [comment]
@fadidahanna added

**Review by fadidahanna — APPROVED** [review]

**Comment by sjpotter** [comment]
missed this, but we should checkout a tag, otherwise this will continue to happen.

**Pull request merged**
