### PR TITLE
Add fsync stats to raft.info

### PR DESCRIPTION
**Pull request by tezc**

### CODE REVIEW

**Review by yossigo — COMMENTED** [review]
@tezc Redis has a monotonic time facility (see `monotonic.h`), which is not currently exposed to modules but might be useful here. Maybe it's an opportunity to add an API for it. WDUT?

**Comment by tezc** [comment]
@yossigo. Is it really useful to have this in module API? It's basically a few lines of code, just a call to `clock_gettime()` and it has no dependency to Redis itself (we'll be just substituting a libc call with an API call). Doesn't this make API bigger without significant benefits?

**Comment by yossigo** [comment]
@tezc To summarize our discussion, the answer is probably yes and the reason is the Redis monotonic timer mechanism supports different implementations including directly accessing a CPU timer on amd64 and arm64 platforms.

**Review by yossigo — DISMISSED** [review]

**Review by yossigo — DISMISSED** [review]

**Comment by tezc** [comment]
Sorry I'll need another approval, CI is failed and need to rebase the PR.

**Review by yossigo — APPROVED** [review]

**Pull request merged**
