### PR TITLE
Add TLS test suite to daily jobs

### PR DESCRIPTION
**Pull request by tezc**
Add a test suite with TLS to daily job.
Require pytest option "--tls" to use tls.

### CODE REVIEW

**Review by yossigo — COMMENTED** [review]
I think we should create a matrix and run both TLS and non-TLS.

**Comment by sjpotter** [comment]
so, we shouldn't a specific TLS test (like now) but run all tests as TLS or not TLS?

**Comment by yossigo** [comment]
@sjpotter Yes, I think that makes sense. We may have some tests that test specific TLS functionality, and these should be optional and only be selected if we build with TLS support.

**Comment by tezc** [comment]
@sjpotter @yossigo Do we really need to run all test suites also with TLS? Isn't that too much? (Just to be fair and limit our github actions usage if we don't need). 

Let's run all tests( CI and daily jobs) with TLS enabled and add one `sanitizer-non-tls` job on linux? Wdyt?

**Comment by yossigo** [comment]
@tezc For CI I think that can be enough, but I'd still run full non-TLS in the daily as well. It's not such a big test and it represents a big chunk of what real world scenarios would look like.

**Comment by tezc** [comment]
@sjpotter @yossigo

 Changed PR a bit according to recent discussions.
- Added one test suite to daily to run tests with TLS
- pytest will requite "--tls" option to use TLS in tests

**Review by yossigo — APPROVED** [review]

**Pull request merged**
