### PR TITLE
Delete unused files

### PR DESCRIPTION
**Pull request by tezc**
Delete unused files

### CODE REVIEW

**Review by fadidahanna — COMMENTED** [review]
I'm not sure we want to remove it, maybe to update.

**Comment by tezc** [comment]
@fadidahanna If someone wants to add valgrind build, I see some value on it. (https://github.com/RedisLabs/redisraft/issues/386) It's not that easy though, requires some work. This file won't help you because it's not accurate. There is no point keeping it until we add valgrind to the CI. 

For the other file, it's not accurate as well. I'm also %100 against it as it relies on your function names, flow control etc. It'll become invalid each time you change something in the code. (Time has proven it, it's been invalid for the last 2 years). I don't think we have time to maintain it. Also, I'm not sure what it brings to the project, so, I don't see any value in it.

**Comment by fadidahanna** [comment]
@tezc, suggest discussing that on a wider forum, adding it to our upcoming meeting agenda.

**Review by sjpotter — APPROVED** [review]

**Comment by tezc** [comment]
@fadidahanna ping ping. Added one more file (I like when we delete things).

**Comment by fadidahanna** [comment]
@tezc - agree with deleting the makefile, can we please do it in a separate PR? I still want to keep the other file as part of our documentation (and hopefully soon we can update them) 🙏

**Comment by fadidahanna** [comment]
@tezc, as was discussed today, we can remove these files, and consider moving to mermaid diagrams for flow documentation.

**Review by fadidahanna — APPROVED** [review]

**Pull request merged**
