### PR TITLE
Use SHUTDOWN command instead of exit()

### PR DESCRIPTION
**Pull request by tezc**
Calling `exit()` from modules is unexpected as Redis won't have a 
chance to do clean up: Closing the sockets, removing pid file etc.
Also, other modules won't get the shutdown callback.

Changing `exit()` to `SHUTDOWN` command to prevent these issues.

### CODE REVIEW

**Comment by fadidahanna** [comment]
So for that reason in order to shut down gracefully, we should keep `RAFT_ERR_SHUTDOWN` from libraft...

**Comment by fadidahanna** [comment]
That was not the original behaviour - see `callRaftPeriodic()` and `handleBeforeSleep()`, but agree with your point. 
Besides that, maybe it's a good time to rename the function `shutdownAfterRemoval()`. We call it not only after node removal, see `cmdRaftNodeShutdown()`.

**Comment by tezc** [comment]
It's a bit confusing but we are actually calling `shutdownAfterRemoval()` when we remove the node. `raft.nodeshutdown` will be sent from the leader to a follower to indicate it has been removed. The reason is when the leader appends removal entry of a follower, it stops replicating entries to that node immediately (In raft, config changes take effect on append, rather than apply).  So, follower will never receive its own removal entry. `raft.nodeshutdown` is a best-effort message from the leader to a removed follower to tell "you have been removed".

Still, sure we can rename the function or add some comments about it, open to suggestions.

**Comment by tezc** [comment]
Added comment for `RAFT.NODESHUTDOWN`

**Review by fadidahanna — APPROVED** [review]

**Pull request merged**
